### ISSUE TITLE
Update LinqPad examples in line with spec

### ISSUE THREAD

**Issue by jonnyry** [nhsconnect/gpconnect-dotnet-examples#1]

**Comment by jonnyry** [comment]
Version repo like other GPC repos?

**Comment by saurabhkjain** [comment]
I have completed the DSTU2 (0.5.0) and STU3(1.1.0) examples in their respective release branches. 

I have also completed the access record structured example (using localhost:19191. This has been pushed to feature 1.2.0 branch
